insert into ssi.LOV_MESSAGE_CODE ( MSG_CODE, MSG_CATEGORIE, MSG_CODE_NAME ) values ( '60204', 'W', 'NEWER MILAGES LESS THAN OLDER ONES' );
insert into ssi.LOV_MESSAGE_CODE ( MSG_CODE, MSG_CATEGORIE, MSG_CODE_NAME ) values ( '60205', 'W', 'INEXACT 0 VALUE IN WORKSHOP OR CUSTOMER INVOICE' );
insert into ssi.LOV_MESSAGE_CODE ( MSG_CODE, MSG_CATEGORIE, MSG_CODE_NAME ) values ( '60206', 'W', 'FIN LONGER OR SHORTER THAN 14 DIGITS' );
insert into ssi.LOV_MESSAGE_CODE ( MSG_CODE, MSG_CATEGORIE, MSG_CODE_NAME ) values ( '60207', 'W', 'CONTRACTS ALREADY ENDED IN THE FUTURE' );
insert into ssi.LOV_MESSAGE_CODE ( MSG_CODE, MSG_CATEGORIE, MSG_CODE_NAME ) values ( '60208', 'W', 'FIN INCLUDES AT LEAST ONE * DIGIT' );