SET SCOPE_DATE=01.01.2011
rem SET DBLINK_SNT_PASSWORD=Tss2007$
SET DBLINK_SNT_PASSWORD=snt
SET DBLINK_DATABASE_NAME=ref.s415mt217.tst

sqlplus -s snt/%DBLINK_SNT_PASSWORD%@%DBLINK_DATABASE_NAME% @set_oos_rev_2_15.sql ROLLBACK %SCOPE_DATE%